# Generated by Django 2.0.1 on 2018-06-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer',
            field=models.BooleanField(default='True'),
        ),
    ]
