# Generated by Django 2.0.1 on 2018-06-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180616_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='correct_ans',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='wrong_ans',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
